# Generated by Django 4.0.3 on 2022-03-22 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('estado', models.CharField(blank=True, max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=20)),
                ('rua', models.CharField(blank=True, max_length=100)),
                ('numero_casa', models.CharField(blank=True, max_length=10)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('telefone', models.IntegerField(blank=True, default=0)),
                ('email', models.EmailField(blank=True, help_text='Ex. clinte@gmail.com', max_length=50)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='DimensaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.FloatField(default=0, help_text='Ex. 8.00', max_length=3)),
                ('largura', models.FloatField(default=0, help_text='Ex. 4.00', max_length=5)),
                ('prof_inicial', models.FloatField(max_length=5)),
                ('prof_final', models.FloatField(default=0, help_text='Ex. 1.40', max_length=3)),
                ('largura_calcada', models.FloatField(blank=True, default=1, help_text='Ex. 1.00', max_length=3)),
                ('espessura', models.CharField(max_length=3)),
                ('fornecedor', models.CharField(max_length=8)),
                ('profundidade_media', models.CharField(default=0, max_length=25)),
                ('area_calcada', models.CharField(max_length=25)),
                ('perimetro', models.CharField(max_length=25)),
                ('m2_facial', models.CharField(max_length=25)),
                ('m2_parede', models.CharField(max_length=25)),
                ('m2_total', models.CharField(max_length=25)),
                ('m3_total', models.CharField(max_length=25)),
                ('m3_real', models.CharField(max_length=25)),
                ('filtro', models.CharField(max_length=30)),
                ('motobomba', models.CharField(max_length=30)),
                ('tampa_casa_maquinas', models.CharField(max_length=30)),
                ('sacos_areia', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, choices=[('Em negociação', 'Em negociação'), ('Contrato', 'Contrato'), ('Encerrado', 'Encerrado')], default='Em negociação', help_text='Status do Orçamento', max_length=15)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimensoes.clientemodel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
