# Generated by Django 3.0.3 on 2020-03-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0002_auto_20200316_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='data',
        ),
    ]
