# Generated by Django 3.0.3 on 2020-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0005_dimensaomodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensaomodel',
            name='profundidade_media',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
