# Generated by Django 3.0.3 on 2020-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0006_auto_20200318_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecificacaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.CharField(max_length=30)),
                ('margem', models.CharField(max_length=30)),
                ('preco', models.CharField(max_length=30)),
                ('filtro_preco', models.CharField(max_length=30)),
                ('motobomba_preco', models.CharField(max_length=30)),
                ('tampa_casa_maquinas_preco', models.CharField(max_length=30)),
                ('sacos_areia_preco', models.CharField(max_length=30)),
                ('perfil_rigido_preco', models.CharField(max_length=30)),
                ('ralo_fundo_preco', models.CharField(max_length=30)),
                ('dispositivo_retorno_preco', models.CharField(max_length=30)),
                ('dispositivo_aspiracao_preco', models.CharField(max_length=30)),
                ('dispositivo_nivel_preco', models.CharField(max_length=30)),
                ('borda_preco', models.CharField(max_length=30)),
                ('skimmer_preco', models.CharField(max_length=30)),
                ('dispositivo_hidromassagem_preco', models.CharField(max_length=30)),
                ('escada_preco', models.CharField(max_length=30)),
                ('timer_preco', models.CharField(max_length=30)),
                ('capa_termica_preco', models.CharField(max_length=30)),
                ('capa_protecao_preco', models.CharField(max_length=30)),
                ('peneira_preco', models.CharField(max_length=30)),
                ('mangueira_preco', models.CharField(max_length=30)),
                ('ponteira_preco', models.CharField(max_length=30)),
                ('adaptador_giratorio_preco', models.CharField(max_length=30)),
                ('haste_aluminio_preco', models.CharField(max_length=30)),
                ('rodo_aspirador_preco', models.CharField(max_length=30)),
                ('escova_preco', models.CharField(max_length=30)),
                ('vinil_preco', models.CharField(max_length=25)),
                ('isomanta_preco', models.CharField(max_length=25)),
                ('perfil_fixo_preco', models.CharField(max_length=25)),
                ('escavacao_preco', models.CharField(default=0, max_length=30)),
                ('construcao_preco', models.CharField(default=0, max_length=30)),
                ('remocao_terra_preco', models.CharField(default=0, max_length=30)),
                ('colocacao_material_preco', models.CharField(default=0, max_length=30)),
                ('contra_piso_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_skimmer_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_borda_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_escada_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_capa_termica_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_capa_protecao_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_tampa_cm_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_vinil_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_filtro_preco', models.CharField(default=0, max_length=30)),
                ('instalacao_motobomba_preco', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='bairro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='area_calcada',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='comprimento',
            field=models.CharField(default=0, help_text='Ex. 8.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='espessura',
            field=models.CharField(choices=[['0.6', '0.6 mm'], ['0.7', '0.7 mm'], ['0.8', '0.8 mm']], max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='fornecedor',
            field=models.CharField(choices=[['sodramar', 'Sodramar'], ['viniplas', 'Viniplas']], max_length=8),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='isomanta_m2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura',
            field=models.CharField(default=0, help_text='Ex. 4.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura_calcada',
            field=models.CharField(blank=True, default=1, help_text='Ex. 1.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='m2_facial',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='m2_parede',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='m2_total',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='m3_real',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='m3_total',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='perfil_fixo_m',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='perimetro',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_final',
            field=models.CharField(default=0, help_text='Ex. 1.40', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_inicial',
            field=models.CharField(default=0, help_text='Ex. 1.20', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='profundidade_media',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='vinil_m2',
            field=models.CharField(max_length=25),
        ),
    ]
