# Generated by Django 3.0.3 on 2020-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0008_remove_precificacaomodel_custo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecificacaoModel',
        ),
        migrations.AddField(
            model_name='dimensaomodel',
            name='preco',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='dimensaomodel',
            name='produto',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='profundidade_media',
            field=models.CharField(max_length=25),
        ),
    ]
