# Generated by Django 3.0.3 on 2020-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0011_auto_20200516_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='telefone',
            field=models.IntegerField(blank=True),
        ),
    ]
