# Generated by Django 3.0.3 on 2020-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0013_remove_dimensaomodel_profundidade_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensaomodel',
            name='profundidade_media',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
