# Generated by Django 3.0.3 on 2020-06-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0014_dimensaomodel_profundidade_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='construcao',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='contra_piso',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='escavacao',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='instalacao_vinil',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='isomanta_m2',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='perfil_fixo_m',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='remocao_terra',
        ),
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='vinil_m2',
        ),
    ]
