# Generated by Django 3.0.3 on 2020-06-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes', '0015_auto_20200604_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensaomodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='telefone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
