# Generated by Django 3.0.3 on 2020-03-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(blank=True, max_length=15)),
                ('rua', models.CharField(blank=True, max_length=100)),
                ('numero_casa', models.CharField(blank=True, max_length=6)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Ex. clinte@gmail.com', max_length=50)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='DimensaoCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_calcada', models.FloatField(max_length=5)),
                ('profundidade_media', models.FloatField(max_length=5)),
                ('area_calcada', models.FloatField(max_length=5)),
                ('perimetro', models.FloatField(max_length=5)),
                ('m2_facial', models.FloatField(max_length=5)),
                ('m2_parede', models.FloatField(max_length=5)),
                ('m2_total', models.FloatField(max_length=5)),
                ('m3_total', models.FloatField(max_length=5)),
                ('m3_real', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DimensaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.FloatField(help_text='Ex. 8.00', max_length=3)),
                ('largura', models.FloatField(help_text='Ex. 4.00', max_length=3)),
                ('prof_inicial', models.FloatField(help_text='Ex. 1.20', max_length=3)),
                ('prof_final', models.FloatField(help_text='Ex. 1.40', max_length=3)),
                ('largura_calcada', models.FloatField(blank=True, default=1, help_text='Ex. 1.00', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EspessuraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(blank=True, max_length=20)),
                ('espessura', models.CharField(choices=[['0.6', '0.6 mm'], ['0.7', '0.7 mm'], ['0.8', '0.8 mm']], help_text='Espessura do vinil', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FiltranteCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=30)),
                ('motobomba', models.CharField(max_length=30)),
                ('tampa_casa_maquinas', models.CharField(max_length=30)),
                ('sacos_areia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(blank=True, max_length=20)),
                ('fornecedor', models.CharField(choices=[['sodramar', 'Sodramar'], ['viniplas', 'Viniplas']], help_text='Fornecedor do vinil', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mao_obraCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escavacao', models.CharField(max_length=30)),
                ('construcao', models.CharField(max_length=30)),
                ('contra_piso', models.CharField(max_length=30)),
                ('motobomba', models.CharField(max_length=30)),
                ('remocao_terra', models.CharField(max_length=30)),
                ('instalacao_vinil', models.CharField(max_length=30)),
                ('filtro', models.ForeignKey(limit_choices_to={'filtro_id'}, on_delete=django.db.models.deletion.CASCADE, to='front.FiltranteCalcModel')),
            ],
        ),
        migrations.CreateModel(
            name='RevestimentoCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinil_m2', models.FloatField(max_length=5)),
                ('isomanta_m2', models.FloatField(max_length=5)),
                ('perfil_fixo_m', models.FloatField(max_length=5)),
                ('espessura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.EspessuraModel')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.FornecedorModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Em negociação'), ('c', 'Contrato'), ('e', 'Encerrado')], default='n', help_text='Status do Orçamento', max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ClienteModel')),
                ('conj_filtrante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.FiltranteCalcModel')),
                ('dimensoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.DimensaoModel')),
                ('dimensoes_calc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.DimensaoCalcModel')),
                ('kit_revestimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.RevestimentoCalcModel')),
                ('mao_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Mao_obraCalcModel')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cliente', 'data'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
    ]
