# Generated by Django 3.0.3 on 2020-02-27 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('rua', models.CharField(blank=True, max_length=100)),
                ('numero_casa', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Ex. clinte@gmail.com', max_length=254)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='DimensaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.CharField(help_text='Ex. 8.00', max_length=3)),
                ('largura', models.CharField(help_text='Ex. 4.00', max_length=3)),
                ('prof_inicial', models.CharField(help_text='Ex. 1.20', max_length=3)),
                ('prof_final', models.CharField(help_text='Ex. 1.40', max_length=3)),
                ('largura_calcada', models.CharField(blank=True, default=1, help_text='Ex. 1.00', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EspessuraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espessura', models.CharField(choices=[['0.6', '0.6 mm'], ['0.7', '0.7 mm'], ['0.8', '0.8 mm']], help_text='Espessura do vinil', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[['sodramar', 'Sodramar'], ['viniplas', 'Viniplas']], help_text='Fornecedor do vinil', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Em negociação'), ('c', 'Contrato'), ('e', 'Encerrado')], default='n', help_text='Status do Orçamento', max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ClienteModel')),
                ('dimensoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.DimensaoModel')),
                ('espessura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.EspessuraModel')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.FornecedorModel')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cliente', 'data'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
    ]
