# Generated by Django 3.0.3 on 2020-03-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensaoCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_calcada', models.FloatField(max_length=5)),
                ('profundidade_media', models.FloatField(max_length=5)),
                ('area_calcada', models.FloatField(max_length=5)),
                ('perimetro', models.FloatField(max_length=5)),
                ('m2_facial', models.FloatField(max_length=5)),
                ('m2_parede', models.FloatField(max_length=5)),
                ('m2_total', models.FloatField(max_length=5)),
                ('m3_total', models.FloatField(max_length=5)),
                ('m3_real', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FiltranteCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=30)),
                ('motobomba', models.CharField(max_length=30)),
                ('tampa_casa_maquinas', models.CharField(max_length=30)),
                ('sacos_areia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mao_obraCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escavacao', models.CharField(max_length=30)),
                ('construcao', models.CharField(max_length=30)),
                ('contra_piso', models.CharField(max_length=30)),
                ('filtro', models.CharField(max_length=30)),
                ('motobomba', models.CharField(max_length=30)),
                ('remocao_terra', models.CharField(max_length=30)),
                ('instalacao_vinil', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentomodel',
            name='espessura',
        ),
        migrations.RemoveField(
            model_name='orcamentomodel',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='espessuramodel',
            name='teste',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedormodel',
            name='teste',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='cidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='email',
            field=models.EmailField(blank=True, help_text='Ex. clinte@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='estado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='comprimento',
            field=models.FloatField(help_text='Ex. 8.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura',
            field=models.FloatField(help_text='Ex. 4.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura_calcada',
            field=models.FloatField(blank=True, default=1, help_text='Ex. 1.00', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_final',
            field=models.FloatField(help_text='Ex. 1.40', max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_inicial',
            field=models.FloatField(help_text='Ex. 1.20', max_length=3),
        ),
        migrations.CreateModel(
            name='RevestimentoCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinil_m2', models.FloatField(max_length=5)),
                ('isomanta_m2', models.FloatField(max_length=5)),
                ('perfil_fixo_m', models.FloatField(max_length=5)),
                ('espessura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.EspessuraModel')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.FornecedorModel')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentomodel',
            name='conj_filtrante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.FiltranteCalcModel'),
        ),
        migrations.AddField(
            model_name='orcamentomodel',
            name='dimensoes_calc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.DimensaoCalcModel'),
        ),
        migrations.AddField(
            model_name='orcamentomodel',
            name='kit_revestimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.RevestimentoCalcModel'),
        ),
        migrations.AddField(
            model_name='orcamentomodel',
            name='mao_obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Mao_obraCalcModel'),
        ),
    ]
