# Generated by Django 3.0.3 on 2020-03-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200317_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensaomodel',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
