# Generated by Django 3.0.3 on 2020-04-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20200408_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precificacaomodel',
            name='custo',
        ),
    ]
