# Generated by Django 3.0.3 on 2020-05-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20200504_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensaomodel',
            name='comprimento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='espessura',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='fornecedor',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='largura_calcada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_final',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensaomodel',
            name='prof_inicial',
            field=models.FloatField(),
        ),
    ]
