# Generated by Django 3.0.3 on 2020-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20200511_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
