# Generated by Django 3.0.3 on 2020-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=30)),
                ('custo', models.BooleanField(max_length=30)),
                ('margem', models.BooleanField(max_length=30)),
                ('preco', models.BooleanField(max_length=30)),
                ('fornecedor', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('caracteristica', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=30)),
                ('custo', models.BooleanField(max_length=30)),
                ('margem', models.BooleanField(max_length=30)),
                ('preco', models.BooleanField(max_length=30)),
            ],
        ),
    ]
