# Generated by Django 3.0.3 on 2020-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='custo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='margem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servico_model',
            name='custo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servico_model',
            name='margem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servico_model',
            name='preco',
            field=models.FloatField(),
        ),
    ]
