# Generated by Django 3.0.3 on 2020-06-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preco', '0002_auto_20200516_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico_Model',
            new_name='ServicoModel',
        ),
    ]
